name: 'Game Of Life Build Badge'
description: 'Build game of life gif seeded by the commit hash that triggered the workflow.'
inputs:
  gol-path:
    description: 'Path of the generated game of life gif'
    required: false
    default: './gol.gif'
  columns:
    description: 'Number of columns in the world grid'
    required: false
    default: 10
  rows:
    description: 'Number of rows in the world grid'
    required: false
    default: 14
  generations: 
    description: 'Number of generations that the game of life runs'
    required: false
    default: 100
runs:
  using: 'node16'
  main: 'main.js'

branding:
  icon: 'grid'  
  color: 'green'
  
